languageCode = "en-us"
title = "Xu`s Blog"
hasCJKLanguage = true
publishDir = "../wxioi.github.io"

theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true


[params]
  title = "Nothing"
  author = "Xu"
  description = "Code more, Word less"
  profilePicture = "/images/avatar.jpg"
  mainSections = ["post"]

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/wxioi/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:wangxu627@gmail.com"


[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "Tools"
  weight = 200
  identifier = "tools"
  url = "/tools/"
